name: GitHub Pages Deploy

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        working-directory: preview
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        working-directory: preview
        env:
          USE_SSH: true
          GIT_USER: git
          CLIENT_ID: efc6c2ca30ec308ce283
          TOKEN_URL: https://polar-falls-16277.herokuapp.com/authenticate/
        run: |
          git config --global user.email "jlvandenhout@gmail.com"
          git config --global user.name "Jeroen van den Hout"
          if [ -e yarn.lock ]; then
            yarn add ./..
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy